name: Petstore Env
values:
  - key: base_url
    enabled: true
    value: 'https://petstore.swagger.io/v2'
  - key: order_id
    enabled: true
    value: ''
  - key: username
    enabled: true
    value: ''
  - key: pet_id
    enabled: true
    value: ''
color: 240
